version: '3.8'

services:
  raffle-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: ${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
        NEXT_PUBLIC_FACTORY_ADDRESS_BASE_SEPOLIA: ${NEXT_PUBLIC_FACTORY_ADDRESS_BASE_SEPOLIA}
        NEXT_PUBLIC_ENABLE_TESTNET: "true"
    container_name: raffle-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - raffle-network

networks:
  raffle-network:
    driver: bridge
